/* GENERATED by tools/generate/generate_identifier_policy.py from identifier_policy_registry.def.
 * Do not edit identifier policy here; edit the canonical registry and regenerate.
 */
#include "frontend/lexer/character.h"
#include "frontend/identifier_identity.h"

int __Lexer_Is_Id_Start__(uint32_t __Scalar__)
{
    return
        (__Scalar__ >= UINT32_C(0x0041) && __Scalar__ <= UINT32_C(0x005A)) ||
        (__Scalar__ >= UINT32_C(0x0061) && __Scalar__ <= UINT32_C(0x007A)) ||
        (__Scalar__ >= UINT32_C(0x0621) && __Scalar__ <= UINT32_C(0x063A)) ||
        (__Scalar__ >= UINT32_C(0x0641) && __Scalar__ <= UINT32_C(0x064A)) ||
        (__Scalar__ >= UINT32_C(0x066E) && __Scalar__ <= UINT32_C(0x066F)) ||
        (__Scalar__ >= UINT32_C(0x0671) && __Scalar__ <= UINT32_C(0x06D3)) ||
        (__Scalar__ >= UINT32_C(0x06E5) && __Scalar__ <= UINT32_C(0x06E6)) ||
        (__Scalar__ >= UINT32_C(0x06EE) && __Scalar__ <= UINT32_C(0x06EF)) ||
        (__Scalar__ >= UINT32_C(0x06FA) && __Scalar__ <= UINT32_C(0x06FC)) ||
        (__Scalar__ >= UINT32_C(0x0750) && __Scalar__ <= UINT32_C(0x077F)) ||
        (__Scalar__ >= UINT32_C(0x08A0) && __Scalar__ <= UINT32_C(0x08C9)) ||
        __Scalar__ == UINT32_C(0x005F) ||
        __Scalar__ == UINT32_C(0x06D5) ||
        __Scalar__ == UINT32_C(0x06FF) ||
        __Identifier_Identity_Ignores_Scalar__(__Scalar__);
}
