/* GENERATED by tools/generate/generate_identifier_policy.py from identifier_policy_registry.def.
 * Do not edit identifier policy here; edit the canonical registry and regenerate.
 */
#include "frontend/lexer/character.h"

/* Checks whether the lexer is ID rest. */
int __Lexer_Is_Id_Rest__(uint32_t __Scalar__)
{
    return
        __Lexer_Is_Id_Start__(__Scalar__) ||
        (__Scalar__ >= UINT32_C(0x0030) && __Scalar__ <= UINT32_C(0x0039)) ||
        (__Scalar__ >= UINT32_C(0x064B) && __Scalar__ <= UINT32_C(0x065F)) ||
        (__Scalar__ >= UINT32_C(0x0660) && __Scalar__ <= UINT32_C(0x0669)) ||
        (__Scalar__ >= UINT32_C(0x06D6) && __Scalar__ <= UINT32_C(0x06DC)) ||
        (__Scalar__ >= UINT32_C(0x06DF) && __Scalar__ <= UINT32_C(0x06E4)) ||
        (__Scalar__ >= UINT32_C(0x06E7) && __Scalar__ <= UINT32_C(0x06E8)) ||
        (__Scalar__ >= UINT32_C(0x06EA) && __Scalar__ <= UINT32_C(0x06ED)) ||
        (__Scalar__ >= UINT32_C(0x06F0) && __Scalar__ <= UINT32_C(0x06F9)) ||
        (__Scalar__ >= UINT32_C(0x08D3) && __Scalar__ <= UINT32_C(0x08FF)) ||
        __Scalar__ == UINT32_C(0x0670);
}
