/* GENERATED by tools/generate/generate_identifier_policy.py from identifier_policy_registry.def.
 * Do not edit identifier policy here; edit the canonical registry and regenerate.
 */
#include "frontend/identifier_identity.h"
#include "support/text/utf8.h"

#include <string.h>

/* Returns the identifier identity ignores scalar. */
int __Identifier_Identity_Ignores_Scalar__(uint32_t __Scalar__)
{
    return
        __Scalar__ == UINT32_C(0x0640);
}

/* Returns the identifier identity normalize scalar. */
static uint32_t __Identifier_Identity_Normalize_Scalar__(uint32_t __Scalar__)
{
    if (__Scalar__ == UINT32_C(0x0622)) return UINT32_C(0x0627);
    if (__Scalar__ == UINT32_C(0x0623)) return UINT32_C(0x0627);
    if (__Scalar__ == UINT32_C(0x0625)) return UINT32_C(0x0627);
    return __Scalar__;
}

/* Returns the identifier semantic scalar. */
static int __Identifier_Next_Semantic_Scalar__(const unsigned char *__Bytes__,
                                                size_t __Length__,
                                                size_t *__Offset__,
                                                uint32_t *__Out_Scalar__)
{
    while (*__Offset__ < __Length__)
    {
        /* Stores the decoded. */
        __Utf8_Decode_Result__ __Decoded__ =
            __Utf8_Decode__(__Bytes__ + *__Offset__, __Length__ - *__Offset__);
        if (!__Decoded__.__Valid__)
        {
            return -1;
        }
        *__Offset__ += __Decoded__.__Width__;
        if (!__Identifier_Identity_Ignores_Scalar__(__Decoded__.__Codepoint__))
        {
            *__Out_Scalar__ = __Identifier_Identity_Normalize_Scalar__(__Decoded__.__Codepoint__);
            return 1;
        }
    }
    return 0;
}

/* Checks whether the identifier identity has content. */
int __Identifier_Identity_Has_Content__(__Text_Slice__ __Text__)
{
    /* References the bytes. */
    const unsigned char *__Bytes__ = (const unsigned char *)__Text__.__Data__;
    /* Stores the offset. */
    size_t __Offset__ = 0U;
    /* Stores the scalar. */
    uint32_t __Scalar__ = 0U;
    /* Stores the operation result. */
    int __Result__;

    if (__Bytes__ == NULL && __Text__.__Length__ != 0U)
    {
        return 0;
    }
    __Result__ = __Identifier_Next_Semantic_Scalar__(
        __Bytes__, __Text__.__Length__, &__Offset__, &__Scalar__);
    return __Result__ == 1;
}

/* Compares the identifier identity. */
int __Identifier_Identity_Equals__(__Text_Slice__ __Left__, __Text_Slice__ __Right__)
{
    /* References the left bytes. */
    const unsigned char *__Left_Bytes__ = (const unsigned char *)__Left__.__Data__;
    /* References the right bytes. */
    const unsigned char *__Right_Bytes__ = (const unsigned char *)__Right__.__Data__;
    /* Stores the left offset. */
    size_t __Left_Offset__ = 0U;
    /* Stores the right offset. */
    size_t __Right_Offset__ = 0U;

    if ((__Left_Bytes__ == NULL && __Left__.__Length__ != 0U) ||
        (__Right_Bytes__ == NULL && __Right__.__Length__ != 0U))
    {
        return 0;
    }
    for (;;)
    {
        /* Stores the left scalar. */
        uint32_t __Left_Scalar__ = 0U;
        /* Stores the right scalar. */
        uint32_t __Right_Scalar__ = 0U;
        /* Stores the left result. */
        int __Left_Result__ = __Identifier_Next_Semantic_Scalar__(
            __Left_Bytes__, __Left__.__Length__, &__Left_Offset__, &__Left_Scalar__);
        /* Stores the right result. */
        int __Right_Result__ = __Identifier_Next_Semantic_Scalar__(
            __Right_Bytes__, __Right__.__Length__, &__Right_Offset__, &__Right_Scalar__);
        if (__Left_Result__ < 0 || __Right_Result__ < 0)
        {
            return 0;
        }
        if (__Left_Result__ == 0 || __Right_Result__ == 0)
        {
            return __Left_Result__ == 0 && __Right_Result__ == 0;
        }
        if (__Left_Scalar__ != __Right_Scalar__)
        {
            return 0;
        }
    }
}

/* Compares the identifier identity C string. */
int __Identifier_Identity_Equals_Cstr__(__Text_Slice__ __Left__, const char *__Right__)
{
    /* Stores the right slice. */
    __Text_Slice__ __Right_Slice__;
    if (__Right__ == NULL)
    {
        return 0;
    }
    __Right_Slice__.__Data__ = __Right__;
    __Right_Slice__.__Length__ = strlen(__Right__);
    return __Identifier_Identity_Equals__(__Left__, __Right_Slice__);
}
